server:
  port: 8080

logging:
  file:
    path: logs/
  level:
    root: INFO
    
spring:
  resources:
    cache:      cachecontrol:        max-age: 12h
    chain:
      enabled: false
  thymeleaf:    mode: HTML
  messages:    basename: messages/messages
  flyway:    enabled: false
  pf4j:
    runtime-mode: development
    enabled: true
    lib-directories:
      - "libs"
    plugin-properties:
      spring:
        main:
          banner-mode: off
    controller:
      base-path: admin

management:  endpoints:    web:      exposure:        include: "*"
