server:
  port: 8080

logging:
  file:
    path: logs/
  level:
    root: INFO
    
spring:
  web:
    resources:
      cache:        cachecontrol:          max-age: 12h
      chain:
        enabled: false
  thymeleaf:    mode: HTML
  messages:    basename: messages/messages
  flyway:    enabled: false
  pf4j:
    runtime-mode: development
    enabled: true
    lib-directories:
      - "libs"
    plugin-properties:
      spring:
        main:
          banner-mode: off
    controller:
      base-path: admin

management:  endpoints:    web:      exposure:        include: "*"

--- 
spring:
  config:    activate:      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 
  pf4j:    plugin-profiles: mysql

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${MYSQL_URL:'jdbc:mysql://localhost/petclinic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC'}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:}
  pf4j:
    runtime-mode: deployment
    plugin-profiles:
      - docker
